---
- hosts: tileservers
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: copy the nginx config file and restart nginx
      template:
        src: etc/nginx/sites-available/tileserver-http
        dest: /etc/nginx/sites-available/tileserver-http
      become: yes
    - name: remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/tileserver-http
        dest: /etc/nginx/sites-enabled/tileserver-http
        state: link
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
